"""empty message

Revision ID: 2f233ed668a5
Revises: 
Create Date: 2018-04-27 22:51:07.599330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f233ed668a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_index('title', table_name='tag')
    op.create_unique_constraint(None, 'tag', ['name'])
    op.drop_column('tag', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'tag', type_='unique')
    op.create_index('title', 'tag', ['title'], unique=True)
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
